[[grammar]]
name = "kdl"
source.git = "https://github.com/tree-sitter-grammars/tree-sitter-kdl.git"
source.rev = "v1.1.0"

[language-server.kdl-lsp]
command = "kdl-lsp"
args = []

[language-server.marksman]
command = "marksman" # If in PATH, just the name works
args = ["server"]

[[language]]
name = "kdl"
scope = "source.kdl"
file-types = ["kdl"]
roots = []
comment-token = "//"
indent = { tab-width = 4, unit = "    " }

grammar = "kdl"
language-servers = ["kdl-lsp"]

